language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-mboy-deploy' ]; then cd .. && eval "mv $currentfolder generator-mboy-deploy" && cd generator-mboy-deploy; fi
notifications:
  hipchat:
    rooms:
      - secure: "fy7h4pMp41OlX8+M3Gn6JF5ErlJJlFXfjsf/qo4SJhPytTKGVKV/f5uSQpCKBxy25THR0gKcKisFEYkHvmZW3t+FeNnCtB96q4MdHb8jGkV2nbcgQUJgoDw6T9be1/kD6YFBQX/uh92jh0A6PnBJuTQQ6HGeC2VbXVJgJHDBRxA="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
